//* PicarioXPO RenderAPI V2 SDK
//*
//* Authors : Picario

/// <reference path="Collections\Collections.ts" />
/// <reference path="Scripts\Pix2.d.ts" />
/// <reference path="String\Base64.ts" />
/// <reference path="String\String.ts" />
/// <reference path="XpoUrlGenerator\ColorKeys.ts" />
/// <reference path="XpoUrlGenerator\DesignKey.ts" />
/// <reference path="XpoUrlGenerator\AspectRatioDesignKey.ts" />
/// <reference path="XpoUrlGenerator\DesignKeyContrast.ts" />
/// <reference path="XpoUrlGenerator\DesignKeys.ts" />
/// <reference path="XpoUrlGenerator\DropXDesignKey.ts" />
/// <reference path="XpoUrlGenerator\DropYDesignKey.ts" />
/// <reference path="XpoUrlGenerator\EntityNameDesignKey.ts" />
/// <reference path="XpoUrlGenerator\FlipDesignKey.ts" />
/// <reference path="XpoUrlGenerator\GeneralKeys.ts" />
/// <reference path="XpoUrlGenerator\GlossDesignKey.ts" />
/// <reference path="XpoUrlGenerator\HeightDesignKey.ts" />
/// <reference path="XpoUrlGenerator\OverlayKey.ts" />
/// <reference path="XpoUrlGenerator\OverlayKeys.ts" />
/// <reference path="XpoUrlGenerator\LocationOverlayKey.ts" />
/// <reference path="XpoUrlGenerator\ModeOverlayKey.ts" />
/// <reference path="XpoUrlGenerator\NameOverlayKey.ts" />
/// <reference path="XpoUrlGenerator\OperationOverlayKey.ts" />
/// <reference path="XpoUrlGenerator\XpoUrlGenerator.ts" />
/// <reference path="XpoUrlGenerator\PlacingPointXDesignKey.ts" />
/// <reference path="XpoUrlGenerator\PlacingPointYDesignKey.ts" />
/// <reference path="XpoUrlGenerator\RepeatDesignKey.ts" />
/// <reference path="XpoUrlGenerator\RotationDesignKey.ts" />
/// <reference path="XpoUrlGenerator\TimeOverlayKey.ts" />
/// <reference path="XpoUrlGenerator\WidthDesignKey.ts" />
/// <reference path="XpoUrlGenerator\TextKey.ts"/>
/// <reference path="XpoUrlGenerator\TextKeys.ts"/>
/// <reference path="XpoUrlGenerator\TextTextKey.ts"/>
/// <reference path="XpoUrlGenerator\TextAlignmentTextKey.ts"/>
/// <reference path="XpoUrlGenerator\TextColorTextKey.ts"/>
/// <reference path="XpoUrlGenerator\TextFontTextKey.ts"/>
/// <reference path="XpoUrlGenerator\TextMultiplierTextKey.ts"/>
/// <reference path="XpoUrlGenerator\TextPlacingPointXTextKey.ts"/>
/// <reference path="XpoUrlGenerator\TextPlacingPointYTextKey.ts"/>
/// <reference path="XpoUrlGenerator\TextSizeTextKey.ts"/>
/// <reference path="XpoUrlGenerator\TextStyleTextKey.ts"/>
/// <reference path="UrlGenerators\FluentXpoUrlColor.ts" />
/// <reference path="UrlGenerators\FluentXpoUrlDesign.ts" />
/// <reference path="UrlGenerators\FluentXpoUrlFactory.ts" />
/// <reference path="UrlGenerators\FluentXpoUrlGenerator.ts" />
/// <reference path="UrlGenerators\FluentXpoUrlObject.ts" />
/// <reference path="UrlGenerators\FluentXpoUrlOverlay.ts" />
/// <reference path="UrlGenerators\FluentXpoUrlText.ts" />
/// <reference path="UrlGenerators\IFluentXpoUrlFactory.ts" />
/// <reference path="UrlGenerators\IFluentUrlGenerator.ts" />
/// <reference path="UrlGenerators\IXpoUrlFactory.ts" />
/// <reference path="UrlGenerators\IXpoCanvasGenerator.ts" />
/// <reference path="UrlGenerators\IXpoUrlGenerator.ts" />
/// <reference path="UrlGenerators\XpoUrlColor.ts" />
/// <reference path="UrlGenerators\XpoUrlDesign.ts" />
/// <reference path="UrlGenerators\XpoUrlObject.ts" />
/// <reference path="UrlGenerators\XpoUrlOverlay.ts" />
/// <reference path="UrlGenerators\XpoUrlRequest.ts" />
/// <reference path="UrlGenerators\XpoUrlRequestCoordinates.ts" />
/// <reference path="UrlGenerators\XpoUrlRequestImage.ts" />
/// <reference path="UrlGenerators\XpoUrlTemplate.ts" />
/// <reference path="UrlGenerators\XpoUrlText.ts" />
/// <reference path="UrlGenerators\XpoUrlTextDecoration.ts" />
/// <reference path="UrlGenerators\UrlGeneratorHelpers.ts" />